# Generated by Django 6.0.4 on 2026-05-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainees/images/'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
